# MyApp v1.0.0
# Author: Developer
# A simple program
# Generated by EXE Forge

APP_NAME = "MyApp"
VERSION  = "1.0.0"

Name = ""
Score = "0"
Health = "100"

def main():
    global Name, Score, Health
    # write any python here
    print("custom code")
    
    while True:
        print("have sex")

if __name__ == "__main__":
    main()
    input("\nPress Enter to exit...")