# MyApp v1.0.0
# Author: Developer
# A simple program
# Generated by EXE Forge

import time
import keyboard

APP_NAME = "MyApp"
VERSION  = "1.0.0"

Name = ""
Score = "0"
Health = "100"

def main():
    global Name, Score, Health
    keyboard.add_hotkey('d', lambda: print(f"Hello from D key!"))
    if keyboard.is_pressed('space'):
        print("Space pressed!")
    keyboard.wait()

if __name__ == "__main__":
    while True:
        main()