# MyApp v1.0.0
# Author: Developer
# A simple program
# Generated by EXE Forge

import time

APP_NAME = "MyApp"
VERSION  = "1.0.0"

Name = ""
Score = "0"
Health = "100"

def main():
    global Name, Score, Health
    print(f"Hello, Master!")
    time.sleep(1)
    Name = input("What is your name? ")

if __name__ == "__main__":
    main()
    input("\nPress Enter to exit...")